# Generated by Django 6.0.2 on 2026-02-15 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='is_anonymous',
            field=models.BooleanField(default=False, help_text='If true, sender names are hidden (for support groups)'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='room_type',
            field=models.CharField(choices=[('direct', 'Direct Message'), ('group', 'Group Chat'), ('support', 'Support Group')], default='direct', max_length=10),
        ),
    ]
