# Generated by Django 6.0.2 on 2026-02-15 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guidance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sessions/'),
        ),
        migrations.AddField(
            model_name='session',
            name='location',
            field=models.CharField(blank=True, help_text='Physical or virtual location', max_length=300),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_type',
            field=models.CharField(choices=[('one_on_one', 'One-on-One'), ('group', 'Group Session'), ('workshop', 'Workshop'), ('sports', 'Sports'), ('cultural', 'Cultural'), ('academic', 'Academic'), ('extracurricular', 'Extracurricular')], max_length=20),
        ),
    ]
